version: '3'
services:
    server:
        build: server
        ports:
            - 8080:8080
        command: python ./main.py
        depends_on:
            - database

    database:
        image: postgres:11.5
        environment:
            POSTGRES_PASSWORD: test
            POSTGRES_USER: test
            POSTGRES_DB: test
